# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  androidBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp ./test -D analyzer-optimize --library hxlua -main Main --interp
