name: Testing
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [alter-state, array, callback, override, pass-variable, return-value, simple-call]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Compiling 
        run: |
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp samples/${{matrix.sample}} -D analyzer-optimize -lib hxlua -main Main -cpp bin -cmd bin/Main
  Rpi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [alter-state, array, callback, override, pass-variable, return-value, simple-call]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Compiling 
        run: |
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp samples/${{matrix.sample}} -D rpi -D analyzer-optimize -lib hxlua -main Main -cpp bin -cmd bin/Main
