# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        sample: [alter-state, array, callback, override, pass-variable, return-value, simple-call]

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp samples/${{matrix.sample}} -D HXCPP_M64 -D analyzer-optimize -lib hxlua -main Main -cpp bin -cmd "bin/Main.exe"
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [alter-state, array, callback, override, pass-variable, return-value, simple-call]

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp samples/${{matrix.sample}} -D HXCPP_M64 -D analyzer-optimize -lib hxlua -main Main -cpp bin -cmd bin/Main
  MacOS:
    runs-on: macos-latest
    strategy:
      matrix:
        sample: [alter-state, array, callback, override, pass-variable, return-value, simple-call]

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Compiling 
        run: |
          haxelib --quiet git hxlua https://github.com/MAJigsaw77/hxlua.git
          haxe -cp samples/${{matrix.sample}} -D HXCPP_M64 -D analyzer-optimize -lib hxlua -main Main -cpp bin -cmd bin/Main
